# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_moodle
      - POSTGRESQL_DATABASE=bitnami_moodle
      - POSTGRESQL_CHARACTER_SET=utf8
      - POSTGRESQL_COLLATE=utf8_general_ci
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  moodle:
    image: docker.io/bitnami/moodle:5.0
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=postgresql
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_TYPE=pgsql
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local