# Config file for Air (https://github.com/cosmtrek/air)

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  full_bin = ""
  include_ext = [".go", ".tpl", ".tmpl", ".html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_file = []
  follow_symlink = true
  log = "stdout"
  poll = false
  delay = 1000
  stop_on_error = true

[log]
  color = "auto"
  time = true

[debug]
  enable = false
  force = false

[watch]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  include_ext = [".go", ".tpl", ".tmpl", ".html"]
